spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${ POSTGRES_USERNAME:postgres}
    password: ${ POSTGRES_PASSWORD:zaq1@WSX}
    url: ${ POSTGRES_URL:jdbc:postgresql://localhost:5432/photonet}
  jpa:
    hibernate:
      ddl-auto: create
---
spring:
  cloud:
    gcp:
      core:
        enabled: false
      storage:
        enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
---
spring:
  config:
    activate:
      on-profile: cloud
  cloud:
    gcp:
      project-id: ringed-choir-337013
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
