spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
    url: jdbc:h2:mem:testdb
  sql:
    init:
      data-locations: classpath:db/data.sql
  jpa:
    defer-datasource-initialization: true
